## Numpy introduction

In [2]:
# import and version

import numpy as np
np.__version__

'1.26.4'

In [3]:
# Built in documentation
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Julian\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\numpy\\__init__.py'>
File:        c:\users\julian\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for f

In [4]:
# Creating Arrays from Python Lists

import random

a1 = np.array([random.randint(0,51) for i in range(10)])
print(a1)

# we can explicitly set the data type

a2 = np.array(a1, dtype= float)
print(a2)

[27  9 20  7 43 16 48 12 17 13]
[27.  9. 20.  7. 43. 16. 48. 12. 17. 13.]


In [5]:
# nested lists result in multi-dimensional arrays

np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# Arrays form scratch: kind of arrays

print(np.zeros(shape=10,dtype= int))
print(np.ones(shape=(3,5),dtype = str)) 
print(np.full(shape = (3, 2), fill_value= np.pi)) #any value

[0 0 0 0 0 0 0 0 0 0]
[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]
[[3.14159265 3.14159265]
 [3.14159265 3.14159265]
 [3.14159265 3.14159265]]


In [7]:
np.linspace(start=0,stop=1,num=5) # values evenly spaced 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# random values
print(np.random.random((3,3))) #uniformly distributed between values
print(np.random.normal(loc=0, scale=1, size=(3, 3))) #uniformly distributed with mean an std
print(np.random.randint(low = 0, high=10, size = (3,3))) # integers
print(np.eye(N=3))

[[0.3298485  0.53712587 0.59734018]
 [0.80619069 0.77106017 0.97571331]
 [0.83750202 0.34251078 0.54217034]]
[[-1.48681192 -0.52041457 -0.91581441]
 [-0.31874095 -0.13451242  0.63047295]
 [ 1.87366188 -0.27046686  1.99254682]]
[[2 7 0]
 [2 8 1]
 [5 9 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Numpy array attributes

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), size (the total size of the array), type or size (memory consumption)

In [9]:
# Defining three random arrays with different dimensionality

np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10,size=6) # One-dimensional array
x2 = np.random.randint(10,size=(3,4)) # two-dimensional array
x3 = np.random.randint(10,size=(3,4,5)) # three-dimensional array

In [10]:
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [12]:
#Property or attributes

print(x3.ndim) # number of dimensions
print(x3.shape) # size of eah dimension
print(x3.size) # total size of the array
print(x3.dtype)  # type of the array
print(x3.itemsize) # in bytes 

3
(3, 4, 5)
60
int32
4


In [16]:
# Indexig and accesing single elements

x1[4]
x1[-1] #end of the array
x2[2,0] # in a multi-dimensional array

1

In [17]:
# Replacing
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
x1[0] = 3.141592 # it has been truncated

print(x1.dtype)
print(x1)

int32
[3 0 3 3 7 9]


In [27]:
# Array slicing: accessing array's subsets

x = np.arange(10)

print(x)
print(x[5:]) # after index 5
print(x[4:7]) # between 2 points
print(x[::2]) # every other element

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]


In [29]:
# Multi-dimensional subarrays

print(x2)
print(x2[:2, :3])  # two rows, three columns
print(x2[:3, ::2])  # all rows, every other column

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]


In [13]:
# reversed

x2[::-1, ::-1]


array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [14]:
# Accessing array rows and columns

print(x2[:, 0])  # first column of x2
print(x2[0, :])  # first row of x2
print(x2[0])  # equivalent to x2[0, :]


[3 7 1]
[3 5 2 4]
[3 5 2 4]


In [20]:
# Subarrays as no-copy views

x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [23]:
# Replacing an element in new subarray

x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [24]:
# if we modify this subarray, we'll see that the original array is changed

print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [25]:
# Creating copies of arrays

x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [26]:
# If we now modify this subarray, the original array is not touched:

x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [27]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [29]:
# Reshaping of arrays

x4 = np.arange(1,10).reshape(3,3)
print(x4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
x = np.array([range(1,7)])
print(x)
x.reshape(2,3)
print(x)

[[1 2 3 4 5 6]]


In [38]:
# row vector via newaxis

x[np.newaxis, :]


array([[[1, 2, 3]]])

In [43]:
# column vector via reshapr
x.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [44]:
# column vector via newaxis
x[:, np.newaxis]

array([[[1, 2, 3, 4, 5, 6]]])

In [ ]:
# Array Concatenation and Splitting
