In [16]:
import numpy as np
# numpy.__version__

In [17]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Julian\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\numpy\\__init__.py'>
File:        c:\users\julian\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for f

In [18]:
L = list(range(10))

for i in L:
    print(type(L[i]))

print(L)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [19]:
L2 = [str(x) for x in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [20]:
[x ** 2 for x in L]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [21]:
# Creating Arrays from Python Lists

L = [1, 4, 2, 5, 3]
Ar = np.array(L)

type(L), type(Ar)

(list, numpy.ndarray)

In [22]:
[str(x) for x in L]

L2 = np.array([1, 4, 2, 5, 3], dtype = 'int')
L2

array([1, 4, 2, 5, 3])

In [23]:
[type(x) for x in L2]

[numpy.int32, numpy.int32, numpy.int32, numpy.int32, numpy.int32]

In [24]:
# nested lists result in multi-dimensional arrays

np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [25]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

In [26]:
np.array([np.random.randint(i,i+15,3) for i in [2, 4, 6]])

array([[ 3,  6, 12],
       [15,  6, 12],
       [19, 18, 13]])

In [27]:
np.zeros(shape= (3,5), dtype='int')
np.ones(shape = (3,5), dtype= 'int')
np.full(shape= (3,5), fill_value= np.pi)
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.random.randint(low=0,high= 50,size = (10,10))

array([[ 9, 35, 25, 12, 16,  2, 35, 36, 16, 43],
       [ 1, 38, 46, 45, 45, 35, 44, 38, 33, 39],
       [48,  8, 48, 19, 25, 42, 11, 20,  2, 41],
       [39, 29, 48, 18, 21, 29, 39,  9, 45, 18],
       [ 5, 39, 15, 35, 48, 23, 37, 12, 35, 10],
       [37,  0,  3, 33, 16, 15, 33, 26, 14, 12],
       [43, 26, 18, 11,  4, 29, 37,  4, 48,  4],
       [22, 16, 34, 48, 39, 21, 32, 43, 12,  6],
       [31,  6, 15,  0, 47, 10, 28, 18, 38, 21],
       [39, 18, 46, 12, 37, 19, 29, 11, 31,  2]])

In [29]:
np.array([np.random.randint(0,50,10) for i in range(10)])

array([[24, 26, 26,  7, 49, 25, 49, 15,  6, 22],
       [31, 48, 32,  4, 29, 28, 36, 33, 39, 45],
       [39, 26, 26, 41, 10,  9,  5, 45, 20, 11],
       [31, 29,  9, 28, 42, 20,  8,  5, 45, 43],
       [32, 39,  4, 33,  5,  8, 32, 32, 45, 22],
       [ 3, 22, 44, 46, 28,  7, 39, 27, 18, 14],
       [31, 45, 25, 16, 41,  8, 27, 18, 13, 24],
       [20, 18, 13, 10, 24, 39, 31, 49,  5, 41],
       [16, 42, 12, 47, 38,  2, 29, 15, 14, 18],
       [ 1,  5, 36, 47, 32, 39, 10, 22, 16,  1]])

In [31]:
# Subarrays as no-copy views

x2 = np.random.randint(low= 1, high=15, size= (3,3))
print(x2)

[[ 4  8  5]
 [ 1  7  3]
 [11  2 14]]


In [32]:
# Let's extract a subset

x2_sub = x2[:2, :2]
print(x2_sub)

[[4 8]
 [1 7]]


In [36]:
# Changing values and cheking original array

x2_sub[0, 0] = 99
print(f'Sub-array: \n {x2_sub}')

print(f'Original array: \n {x2}') # The value changed

Sub-array: 
 [[99  8]
 [ 1  7]]
Original array: 
 [[99  8  5]
 [ 1  7  3]
 [11  2 14]]


In [38]:
# To avoid it, we can create a copy

x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  8]
 [ 1  7]]


In [39]:
x2_sub_copy[0, 0] = 42
print(f'Modified array: \n {x2_sub_copy}')

print(f'Original array: \n {x2}')


Modified array: 
 [[42  8]
 [ 1  7]]
Original array: 
 [[99  8  5]
 [ 1  7  3]
 [11  2 14]]


### Reshaping of Arrays

In [40]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
x = np.array([1, 2, 3])

# row vector via reshape
print(f'Row vector: \n {x.reshape((1, 3))}')

# column vector via reshape
print(f'Column vector: \n {x.reshape((3, 1))}')

Row vector: 
 [[1 2 3]]
Column vector: 
 [[1]
 [2]
 [3]]


### Array Concatenation and Splitting

In [44]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [45]:
# More than two arrays at once

z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [52]:
# Even with two-dimensional arrays

grid = np.arange(1,7).reshape(2,3)
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [56]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [57]:
# Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [58]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

## Universal functions

Numpy provides an easy and flexible interface to optimized computation with arrays of data.
The key to making fast is to use **vectorized operation** generally implemented through **NumPy's universal functions** (ufuncs).

In [2]:
# looping over arrays to operate on each element

import numpy as np

np.random.seed(0)

def compute_reciprocals(x):
    output = np.empty(len(x))
    for i in range(len(x)):
        output[i] = 1 / x[i]
    return output

x = np.random.randint(1,10,size=5)
print(f'Original vector: {x}')
print(f'Reciprocals vector: {compute_reciprocals(x)}')

Original vector: [6 1 4 4 8]
Reciprocals vector: [0.16666667 1.         0.25       0.25       0.125     ]


In [3]:
# Measuring the execution time 

big_array = np.random.randint(1,100,size = 1000000)
%timeit compute_reciprocals(big_array)

216 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
# Vectorized operation
#his can be accomplished by simply performing an operation on the array, which will then be applied to each element

%timeit (1 / big_array)

4.98 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
# We can operate two arrays

a = np.arange(5)
b = np.arange(1,6)

print(f'Operation between vectors:\n  Vectors \n: {a , b}')
print(f'Operation: \n {a / b}')

Operation between vectors:
  Vectors 
: (array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))
Operation: 
 [0.         0.5        0.66666667 0.75       0.8       ]


In [12]:
c = np.arange(9).reshape((3,3))
2 ** c

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [15]:
# Array arithmetic
# Ufuncs use python's native arithmetic operators

x = np.arange(4)
print("x =", x) 
print("x + 5 =", x + 5) # np.add()
print("x - 5 =", x - 5) # np.subtract()
print("x * 2 =", x * 2) # np.multiply()
print("x / 2 =", x / 2) # np.divide()
print("x // 2 =", x // 2)  # np.floor_divide()
print("-x     = ", -x) # np.negative()
print("x ** 2 = ", x ** 2) # np.power()
print("x % 2  = ", x % 2) # np.mod()

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [22]:
x = np.arange(start= -2,stop=3)
abs(x) # Absolute value
np.absolute(x)

array([2, 1, 0, 1, 2])

In [23]:
# Trigonometric functions

theta = np.linspace(0, np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [24]:
# Exponents and logarithms

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [25]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


**Oficial documentation:** 

**Numpy:** https://numpy.org/ 

**Scipy:** https://scipy.org/

### Aggregations: Min, Max, and Everything In Between

In [27]:
# Summing 

L = np.random.random(10)
L, sum(L)

(array([0.39274799, 0.69444295, 0.71234984, 0.64181726, 0.14519247,
        0.91796933, 0.02800916, 0.53171561, 0.34500616, 0.80695872]),
 5.2162094917774615)

In [28]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

228 ms ± 47.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.5 ms ± 226 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
