## Numpy introduction

In [5]:
# import

import numpy as np
np.__version__

'1.26.4'

In [8]:
# Built in documentation
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Julian\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\numpy\\__init__.py'>
File:        c:\users\julian\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for f

In [29]:
# Creating Arrays from Python Lists

import random

a1 = np.array([random.randint(0,51) for i in range(10)])
print(a1)

# we can explicitly set the data type

a2 = np.array(a1, dtype= float)
print(a2)

[41 33 22 33 34 38 10 50 35 35]
[41. 33. 22. 33. 34. 38. 10. 50. 35. 35.]


In [21]:
# nested lists result in multi-dimensional arrays

np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [44]:
# Arrays form scratch

print(np.zeros(shape=10,dtype= int))
print(np.ones(shape=(3,5),dtype = str)) 
print(np.full(shape = (3, 2), fill_value= np.pi)) #any value

[0 0 0 0 0 0 0 0 0 0]
[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]
[[3.14159265 3.14159265]
 [3.14159265 3.14159265]
 [3.14159265 3.14159265]]


In [45]:
np.linspace(start=0,stop=1,num=5) # values evenly spaced 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [57]:
# random values
print(np.random.random((3,3))) #uniformly distributed between values
print(np.random.normal(loc=0, scale=1, size=(3, 3))) #uniformly distributed with mean an std
print(np.random.randint(low = 0, high=10, size = (3,3))) # integers
print(np.eye(N=3))

[[0.27493363 0.83917913 0.04993158]
 [0.72661416 0.76184243 0.37403662]
 [0.68266583 0.29820659 0.4320916 ]]
[[-0.01276638 -1.10850543  0.56569073]
 [ 0.3434158   2.22825472 -0.21595234]
 [-1.49583169 -1.21573695 -0.17880285]]
[[2 1 4]
 [6 8 3]
 [2 4 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Numpy arrat attributes

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), size (the total size of the array), type or size (memory consumption)

In [69]:
# Defining three random arrays with different dimensionality

np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10,size=6) # One-dimensional array
x2 = np.random.randint(10,size=(3,4)) # two-dimensional array
x3 = np.random.randint(10,size=(3,4,5)) # three-dimensional array

In [73]:
x3.ndim, x3.shape, x3.size, x3.dtype, x3.itemsize #Property or attributes

(3, (3, 4, 5), 60, dtype('int32'), 4)

In [74]:
# Indexig and accesing single elements

x1[4]
x1[-1] #end of the array
x2[2,0] # in a multi-dimensional array


1

In [75]:
# Replacing
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
# https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html